### ISSUE TITLE
Doesn't work on Mac OS X 

### ISSUE THREAD

**Issue by sinacek** [dperson/torproxy#2]
Hi, thank you for your image, but it doesn't work on mac. Today I tried 20 images and no one works on mac, so I tried yours on Ubuntu and it works.

Doesn't work means, that command curl -x http://172.17.0.2:8118 http://jsonip.com/ get  curl: (7) Failed to connect to 172.17.0.2 port 8118: Operation timed out

**Comment by dperson** [comment]
I don't have the docker OSX beta, so can't test directly... I'm assuming that you're running a proxy container reusing the network stack of the `dperson/openvpn-client`.

 * First thing to test: does your Mac even have network access to the container network? `ping 172.17.0.2`
  * If you don't check you routing table in OSX: `netstat -r` see if it knows to send traffic to the Linux VM (I think that this is where the issue is).
   * Either use the `-p 8118:8118` flag when launching your proxy container to have the VM forward the traffic (and use it's IP to connect to).
   * Or you'll have to manually add the route until Docker starts doing it automagically `route add -net 172.17.0.0 netmask 255.255.0.0 gw <IP_of_Linux_VM>` (replace "<IP_of_Linux_VM>" with the actual IP address)
  * If you have network access, verify that the container is actually listening `docker exec -it <container_name> ss -lntp | grep 8118` (replace "<container_name>" with the name of your proxy container)
If the above doesn't point you to where the issue is I'd really have to probably mess with it myself to try and figure it out...
